[package]
name = "naromat"
version = "0.1.0"
authors = ["Hitomaru Horino <type10tk@kahi-sv.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"