name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Cache tarpaulin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin/cargo-tarpaulin
        key: ${{ runner.os }}-naromat-${{ hashFiles(format('{0}{1}', github.workspace, '/.github/workflows/rust.yml')) }}
        restore-keys:
          ${{ runner.os }}-naromat-
    - name: Coveralls
      run: cargo tarpaulin --coveralls ${{ secrets.COVERALLS_TOKEN }}
