name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cache tarpaulin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin/cargo-tarpaulin
        key: ${{ runner.os }}-naromat-${{ hashFiles(format('{0}{1}', github.workspace, '/.github/workflows/rust.yml')) }}
        restore-keys:
          ${{ runner.os }}-naromat-
    - name: Install tarpaulin
      if: steps.cache-tarpaulin.outputs.cache-hit != 'true'
      run: cargo install cargo-tarpaulin
    - name: Coveralls
      run: cargo tarpaulin --coveralls ${{ secrets.COVERALLS_TOKEN }}
